# Generated by Django 3.2.5 on 2021-07-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableTransactions',
            fields=[
                ('telegram_id', models.TextField(primary_key=True, serialize=False, verbose_name='телега')),
                ('transaction_id', models.TextField(blank=True, null=True, verbose_name='транзакция')),
                ('wallet', models.TextField(blank=True, null=True, verbose_name='кошелек')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'db_table': 'table_transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableUsers',
            fields=[
                ('telegram_id', models.TextField(primary_key=True, serialize=False, verbose_name='телега')),
                ('user_language', models.TextField(blank=True, null=True, verbose_name='язык')),
                ('hash', models.TextField(blank=True, null=True, verbose_name='токен')),
                ('last_trans', models.TextField(blank=True, null=True, verbose_name='последняя транзакция')),
                ('last_wallet', models.TextField(blank=True, null=True, verbose_name='последний кошелек')),
                ('limits', models.IntegerField(blank=True, null=True, verbose_name='запуски')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'table_users',
                'managed': False,
            },
        ),
    ]
